# Generated by Django 6.0.3 on 2026-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
