# Generated by Django 6.0.3 on 2026-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0002_alter_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='has_outlets',
        ),
        migrations.RemoveField(
            model_name='location',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_quiet',
        ),
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Done')], default=0, max_length=8),
        ),
    ]
