# Generated by Django 6.0.3 on 2026-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0003_remove_location_has_outlets_remove_location_has_wifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(db_index=True, default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
