# Generated by Django 6.0.3 on 2026-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0004_location_google_place_id_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
