# Generated by Django 6.0.3 on 2026-04-28 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0008_create_aiaggregateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaggregateprofile',
            name='laptop_friendly',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='aiaggregateprofile',
            name='noise_level',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='aiaggregateprofile',
            name='overall_corwdness',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='aiaggregateprofile',
            name='overall_rating',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='aiaggregateprofile',
            name='study_friendly',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
