# Generated by Django 6.0.3 on 2026-06-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0011_aiprofilegenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='besttime_forecast_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='besttime_live_busyness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='besttime_live_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='besttime_venue_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BestTimeCrowdnessJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetching', 'Fetching BestTime data'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besttime_jobs', to='coffeeshops.location')),
            ],
            options={
                'db_table': 'app_besttimecrowdnessjob',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['location', 'status'], name='app_besttim_locatio_36f1aa_idx'), models.Index(fields=['updated_at'], name='app_besttim_updated_d5d420_idx')],
            },
        ),
    ]
