# Generated by Django 6.0.3 on 2026-06-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0012_location_besttime_forecast_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiaggregateprofile',
            name='overall_corwdness',
        ),
    ]
