from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS app_schoolclass (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name varchar(255) NOT NULL,
                            class_type varchar(20) NOT NULL DEFAULT 'course',
                            day_of_week smallint NOT NULL,
                            start_time time NOT NULL,
                            end_time time NOT NULL,
                            location varchar(255) NOT NULL DEFAULT '',
                            created_at timestamp with time zone NOT NULL DEFAULT now(),
                            user_id integer NOT NULL REFERENCES auth_user (id) DEFERRABLE INITIALLY DEFERRED
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS app_schoolclass;",
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="schoolclass",
                    name="class_type",
                    field=models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("seminar", "Seminar"),
                            ("lab", "Lab"),
                            ("workshop", "Workshop"),
                            ("tutorial", "Tutorial"),
                        ],
                        default="course",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
