# Generated by Django 6.0.3 on 2026-04-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schoolclass_class_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='app_task',
        ),
        migrations.AlterModelTable(
            name='taskblock',
            table='app_taskblock',
        ),
    ]
