# Generated by Django 6.0.3 on 2026-04-11 01:20

from django.db import migrations


def _rename_tables_forward(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if "app_assignment" in existing_tables and "app_task" not in existing_tables:
        schema_editor.execute("ALTER TABLE app_assignment RENAME TO app_task;")


def _rename_tables_backward(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if "app_task" in existing_tables and "app_assignment" not in existing_tables:
        schema_editor.execute("ALTER TABLE app_task RENAME TO app_assignment;")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schoolclass_class_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_tables_forward,
                    _rename_tables_backward,
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='assignment',
                    table='app_task',
                ),
                migrations.AlterModelTable(
                    name='taskblock',
                    table='app_taskblock',
                ),
            ],
        ),
    ]
