# Generated by Django 6.0.3 on 2026-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_coffee_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('homework', 'Homework'), ('project', 'Project'), ('exam', 'Exam'), ('reading', 'Reading'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='lecturer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
