# Generated by Django 6.0.3 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignment_category_assignment_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
