# Generated by Django 6.0.3 on 2026-06-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_assignment_completed_at'),
        ('coffeeshops', '0011_aiprofilegenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='study_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='coffeeshops.location'),
        ),
    ]
